version: '3'

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    restart: always
    expose:
      - "6333"
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
  
  embedbase:
    container_name: embedbase-hosted
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: python3 main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - OPENAI_API_KEY=[Your OpenAI Key]