version: '3'

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    restart: always
    expose:
      - "6333"
    network_mode: host
    volumes:
      - ./qdrant_storage:/qdrant/storage
  
  embedbase:
    container_name: embedbase
    image: takiwang/embedbase
    expose:
      - "8000"
    network_mode: host
    command: python3 main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - API_TYPE=[Your API Type]
      - AZURE_API_KEY=[Your OpenAI Key]
      - AZURE_API_BASE=[Your OpenAI Base URL]
      - AZURE_API_VERSION=[Your OpenAI Version]
      - AZURE_DEPLOYMENT_ID=[Your OpenAI Deployment ID]
      - QDRANT_URL=[Your Qdrant URL]
      - QDRANT_API_KEY=[Your Qdrant API Key]