version: '3'

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    restart: always
    expose:
      - "6333"
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
